### ISSUE TITLE
Identify pain points and solution of Sage benchmarking infrastructure

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#51]
This Epic is a Sage objective for 2021 Q3-Q4.

Achieved: Identify and document the limitation of the current benchmarking infra
Stretch: Identify solutions for limitations identified and start implementing them

See [Research & Benchmarking Technology Objectives Dashboard](https://lucid.app/lucidchart/invitations/accept/inv_c7014eed-2dbc-4630-b59c-a529c9b3c696)

Tasks:

- [ ] [Brainstorm pain points and solution in Lucidchart](https://lucid.app/lucidchart/59e57199-fde9-48c0-aaef-b1ff3bffcf31/edit?invitationId=inv_fe5d7b5b-5a14-40eb-8328-9898e52194aa)
- [ ] Document the pain points and solution identified (Google Doc)
- [ ] Start implementing solutions
  - The solution that we will address is the centralization and monitoring of logs using ELK

**Comment by thomasyu888** [comment]
Update link with figjam: https://www.figma.com/file/rFROcDsYOZ9Pc4ZYuWZSSV/Pain-Points-and-Solutions
