### ISSUE TITLE
Push CCKP tools data to RDP Elasticsearch instance

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#56]
Push CCKP tool data to the RDP Elasticsearch instance created by Dave. Start pushing a sample of data.

## Task

- [x] Get access to the Elasticsearch instance
  - Kibana: http://search.cd2h.org:5601
- [x] Learn how to push data to an Elasticsearch instance
  - An example is given in https://github.com/biothings/biothings.crawler
- [x] Write a Python script that read tool data in JSON format and push them to the Elasticsearch instance
  - Depends on #55

**Comment by tschaffter** [comment]
Done in [this PR](https://github.com/Sage-Bionetworks/rdptoolkit/pull/1)
