### ISSUE TITLE
Update Dependabot configuration to support github-actions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/research-benchmarking-technology#8]
## Motivation

Get notification when a new version of a GH Action is available and easy update with Dependabot PR.

## Resources

- https://github.com/OpenAPITools/openapi-generator/blob/master/.github/dependabot.yml

## Task

- [x] Add to ROCC project
- [ ] Add to NLP Sandbox project

**Comment by tschaffter** [comment]
I created the team @Sage-Bionetworks/rocc-maitainers and assigned it as reviewer to Dependabot's updates.

**Comment by tschaffter** [comment]
Using the existing team @nlpsandbox/maintainers for the NLP Sandbox alerts.

NLP Sandbox repositories:

- [ ] aws-cloudformation
- [ ] data-node
- [ ] data-node-client
- [ ] date-annotator-example
- [ ] date-annotator-example-java
- [ ] date-annotator-stub
- [ ] discord
- [ ] docker-elk
- [ ] nlpsandbox
- [ ] nlpsandbox-client
- [ ] nlpsandbox-controller
- [ ] nlpsandbox-schemas
- [ ] nlpsandbox-website-synapse
- [ ] person-name-annotator-example
- [ ] phi-deidentifier
- [ ] phi-deidentifier-app
- [ ] physical-address-annotator-example
